version: "3.8"
<<<<<<< HEAD
volumes:
  php-fpm-socket:
  db-store:
services:
  app:
    build: ./infra/docker/php
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ./backend:/work/backend

  web:
    build: ./infra/docker/nginx
    ports:
      - 172.22.79.199:80:80
      - 172.22.79.199:443:443
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ./backend:/work/backend
      

  db:
    build: ./infra/docker/mysql
    ports:
      - 3306:3306
    volumes:
      - db-store:/var/lib/mysql
=======
services:
  app:
    build: ./infra/php
    volumes:
      - ./backend:/work

  web:
    image: nginx:1.18-alpine
    ports:
      - 10080:80
    volumes:
      - ./backend:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work

  db:
    build: ./infra/mysql
    volumes:
      - db-store:/var/lib/mysql
    
    
>>>>>>> origin/main

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=phper
      - PMA_PASSWORD=secret
    links:
      - db
    ports:
        - 8080:80
    volumes:
        - "./phpmyadmin/sessions:/sessions"

<<<<<<< HEAD

=======
volumes:
  db-store:
>>>>>>> origin/main
